# 这是帮助您开始使用 Actions 的基本工作流程

姓名：名称：CI

# 控制工作流何时运行
在：
  # 在推送或拉取请求事件上触发工作流程，但仅限于“主”分支# 在推送或拉取请求事件上触发工作流程，但仅限于“主”分支
  推：
    分支：[ “主要” ]    分支：[“主要”] 
  拉请求：
    分支：[ “主要” ]    分支：[“主要”] 

  # 允许您从“操作”选项卡手动运行此工作流程# 允许您从“操作”选项卡手动运行此工作流程
  工作流程_调度：

# 工作流程运行由一个或多个可以顺序或并行运行的作业组成
工作：
  # 该工作流程包含一个名为“build”的作业# 该工作流程包含一个名为“build”的作业
  建造：
    # 作业将运行的运行器类型# 作业将运行的运行器类型
    运行：    运行：ubuntu-latest

    # 步骤表示将作为作业的一部分执行的一系列任务# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 在 $GITHUB_WORKSPACE 下签出您的存储库，以便您的作业可以访问它
      -用途：      - 使用：actions/checkout@v3

      # 使用 runner shell 运行单个命令# 使用 runner shell 运行单个命令
      -姓名：      - 名称：运行一行脚本
        跑步：        运行： echo 你好，世界！

      # 使用 runner shell 运行一组命令# 使用 runner shell 运行一组命令
      -姓名：      - name: 运行多行脚本
        运行：|
          echo 添加其他要构建的操作，
          echo 测试，并部署您的项目。
